libnvme: Add NVMe MI Features: Controller Metadata (0x7E) and Namespa…
linux-nvme/libnvme pull request #145
Opened 2021-12-13 18:11 UTC by ikegami-t

…ce Metadata (0x7F).

Splitted between nvme-cli and libnvme.

Commit b8a403b ("Add NVMe MI Features: Controller Metadata (0x7E) and Namespace Metadata (0x7F).")
Commit 2ae875d ("fix whitespace damage")
Signed-off-by: Nate Roiger <nate.roiger@hpe.com>
Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>

2021-12-13 19:17 UTC, igaw requested changes
Thanks for working on these missing commits.

2021-12-13 19:17 UTC, igaw commented on src/nvme/types.h
> +	NVME_MI_FEAT_NS_METADATA	= 0x7F,
These should follow the name scheme from above and also placed accordingly their value, that is before NVME_FEAT_FID_SW_PROGRESS.

2021-12-13 19:17 UTC, igaw commented on src/nvme/types.h
> +struct nvme_mi_host_metadata_element_desc {
Not so sure about the 'mi' in the name here. It doesn't show up in the spec.

2021-12-13 19:17 UTC, igaw commented on src/nvme/util.c
> +		*len = 4096;
After looking at the rest of the function, it looks like the idea is to define the struct to the right size and just do a sizeof(struct nvme_mi_host_metadata) here.

2021-12-14 16:04 UTC, ikegami-t commented
> Thanks for working on these missing commits.

Thanks for your reviewing. I have just fixed the chenged for the comments and force-pushed them into both libnvme and nvme-cli so please review again.

2021-12-17 16:42 UTC, closed without merging

2021-12-17 16:43 UTC, igaw commented
Thanks for helping out. I've applied the version in #146 was based on your work here.