MI: Add endpoint iterators, and allow scanning from MCTP endpoints on dbus
linux-nvme/libnvme pull request #396
Opened 2022-06-22 04:26 UTC by jk-ozlabs

The MCTP userspace infrastructure provides the set of discovered endpoints over dbus. This series adds a facility to query that list for endpoints that report support for the NVMe-MI protocol, and add them to the `nvme_root_t`.

With that information, we can add iterators to traverse the results of the scan.

This dbus mechanism is conditional on the low-level sdbus interface library, provided by libsystemd, and is enabled/disabled at `meson setup`.

As always, comments, queries, etc. are most welcome.

2022-06-22 06:13 UTC, igaw requested changes
- add to all function/definitions in mi.h proper documentation. I just realized it really looks a bleak right now.
 - use consistently `/* */` for comments and not `//` for consistency reasons. 
 - I don't think we should mix the library code and a D-Bus service daemon. If I understood it correctly, the D-Bus parts are not depending on any internal APIs, so it could be placed into a separate file (even directory).

2022-06-22 10:34 UTC, jk-ozlabs commented
> * add to all function/definitions in mi.h proper documentation. I just realized it really looks a bit bleak right now.

Sure, can do! I'll add those as a preliminary patch.
 
> * use consistently `/* */` for comments and not `//` for consistency reasons.

No problem, will update.
 
> * I don't think we should mix the library code and a D-Bus service daemon. If I understood it correctly, the D-Bus parts are not depending on any internal APIs, so it could be placed into a separate file (even directory).

The dbus service daemon isn't included here, that's a separate component (part of the general MCTP tools, at https://github.com/CodeConstruct/mctp ). This addition requests the discovered NVMe-capable endpoints from that daemon. Is that still OK?

2022-06-22 12:37 UTC, jk-ozlabs commented
> misread it then

On re-reading my PR description, I totally see how it could be read that way - sorry for any ambiguity.

To clarify: `mctpd`, shipped as part of the general MCTP tools, performs MCTP endpoint discovery and enumeration - somewhat like DHCP, but also keeping track of the protocols advertised by each endpoint.

These patches add support for libnvme to query `mctpd` for endpoints that support the NVMe-over-MCTP protocol, and then use that to populate the endpoints list.

I'll update the series with your requested changes tomorrow, might be best to save any further review for then :)

2022-06-22 13:33 UTC, igaw commented
Thanks for explaining. I think this explanation could (should?) go into our documentation, e.g. in doc/mi.rst(.in).

2022-06-23 07:30 UTC, jk-ozlabs commented
Looks like I hit a difference in the init process from https://github.com/linux-nvme/libnvme/pull/397 ; fixing now.

2022-06-23 07:32 UTC, igaw commented
The tests are working! Hurray!

2022-06-23 07:43 UTC, jk-ozlabs commented
Any objections from exporting `nvme_mi_init_ep()` in the symbol map, but leaving out of the public headers?

This would allow our tests to use the "actual" mi_init, rather than re-implementing it (and then getting it wrong) within the test code.

2022-06-23 07:52 UTC, igaw commented
Ooops, sorry about this. Please go ahead and export it. Not sure why it's not in the header.

2022-06-23 07:54 UTC, jk-ozlabs commented
> Ooops, sorry about this. Please go ahead and export it. Not sure why it's not in the header.

It's intentionally not in the (public) header because it's only part of the core <--> transport interface, not the public interface.

We do have it in `src/private.h` so that it's available for transports to use, but they don't need the export in the .map, of course.

I'd still like to keep it in private.h, but it's a little unconventional to have it in the .map but not headers, I guess.

2022-06-23 07:56 UTC, igaw commented
Got it. Maybe move the symbol to an extra section in the map? So that we can later remove it if we want to?

2022-06-23 07:58 UTC, jk-ozlabs commented
ooh, that's a good idea, I'll check it out.

(the tests define their own fake transport, so the awkwardness here is that the test code is both providing a transport, as well as using the public API...)

2022-06-23 08:09 UTC, jk-ozlabs commented
OK, proposed in #400, but I'm happy to come up with a different approach if you prefer.

Once that's sorted I'll rebase this.

2022-06-23 08:18 UTC, igaw commented
The whole thing is a tradeoff. I think it's an acceptable compromise for the time being.

2022-06-24 06:07 UTC, jk-ozlabs commented
Rebased onto the test library changes, and re-tested on hardware.

2022-06-24 06:31 UTC, igaw approved these changes
Looks good.  The documentation bits  about the D-Bus interaction are really helpful.

There is just the `strlen`-`malloc` dance which is a bit awkward and could really make use of `asprintf`

2022-06-24 06:31 UTC, igaw commented on src/nvme/mi-mctp.c
> +		snprintf(s, 100, "net %d eid %d", mctp->net, mctp->eid);
asnprintf() could be used here.

2022-06-24 06:31 UTC, igaw commented on src/nvme/mi.c
> +			snprintf(s, len, "%s: %s", ep->transport->name, ts);
the `strlen` and `malloc` dance looks a bit awkward. `asprintf` avoids this altogether

2022-06-24 07:21 UTC, jk-ozlabs commented
Sure - if you're OK with using `asprintf`, I'll update that.

I might even make the transport->desc API take a fixed-sized string, avoiding one of those allocations.

2022-06-24 07:23 UTC, igaw commented
There are already users of asprintf in nvme-cli and libnvme. This ship has sailed :)

2022-06-24 07:45 UTC, jk-ozlabs commented
now with less `malloc`!

2022-06-24 08:00 UTC, merged