util: Add ipaddrs_eq() to check whether two IP addresses are equal
linux-nvme/libnvme pull request #652
Opened 2023-05-19 17:42 UTC by martin-belanger

This is prep work for issue: https://github.com/linux-nvme/libnvme/issues/648

The new function `ipaddrs_eq()` can be used to compare IP addresses. Once https://github.com/linux-nvme/libnvme/pull/647 gets merged (assuming it does get merged), I will submit another PR to use `ipaddrs_eq()` everywhere that we compare IP addresses.

2023-05-24 09:08 UTC, igaw requested changes
Looks good and we should use this function where ever we compare the IP address (nvme-cli `__nvme_lookup_ctrl`)

2023-06-01 17:07 UTC, martin-belanger commented on test/test-util.c
> + * Copyright (c) 2023 Code Construct
D'oh! This was a copy/paste issue. Just resubmitted with proper Copyright.

2023-06-02 11:37 UTC, igaw approved these changes

2023-06-02 11:37 UTC, merged

2023-06-02 11:41 UTC, igaw commented
As usual, as soon I press accept, I figure out that I missed something. 

Anyway, I think we should prefix the function with `nvme_` and it also `libnvme.map `needs to be updated to be useful outside of libnvme

2023-06-02 12:21 UTC, martin-belanger commented
> As usual, as soon I press accept, I figure out that I missed something.

:smile: 

> Anyway, I think we should prefix the function with `nvme_` and it also `libnvme.map` needs to be updated to be useful outside of libnvme

Ok. I will do it right now.