libnvme: add lockdown log page support(LID : 0x14)
linux-nvme/libnvme pull request #887
Opened 2024-09-18 13:05 UTC by ankitvvsoni

Adding command APIs for inband, out of band, structures and enums for lockdown log page (LID : 0x14).

2024-09-23 09:41 UTC, igaw requested changes
same naming updates needed, rest looks good.

2024-09-23 09:41 UTC, igaw commented on src/nvme/types.h
> +	ADMIN_CMD	= 0x0,
Please prefix all the enums accordingly (also further down).

2024-09-23 09:41 UTC, igaw commented on src/nvme/types.h
> +	__u8	csss;
The field is named `cfila` and the spec, please use this name here.

2024-09-23 09:41 UTC, igaw commented on src/nvme/types.h
> +	__u8	length;
`lngth` is used as field name in the spec, I  think we should also use it here, just to be consistent.

2024-09-23 10:24 UTC, ankitvvsoni commented
@igaw, addressed review comments.

2024-10-01 04:19 UTC, ankitvvsoni commented
hi @igaw ,
Changes you have suggested are addressed. can you provide your review?

Thanks

2024-10-23 11:43 UTC, merged

2024-10-23 11:44 UTC, igaw commented
Sorry for the late response. Lost in the inbox situation ... 
Anyway, thanks!